name: Run Pytest Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    if: >-
      ${{
        secrets.YOUTUBE_DATA_API_KEY != '' &&
        secrets.SERPER_API_KEY != '' &&
        secrets.GROQ_API_KEY != ''
      }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ask_web_youtube/requirements.txt
          pip install pytest

      - name: Run tests
        working-directory: ask_web_youtube
        run: make tests

  skip-log:
    runs-on: ubuntu-latest
    if: >-
      ${{
        secrets.YOUTUBE_DATA_API_KEY == '' ||
        secrets.SERPER_API_KEY == '' ||
        secrets.GROQ_API_KEY == ''
      }}
    steps:
      - name: Log skipped test info
        run: |
          echo "❕ Skipping tests: One or more required secrets are missing."
          echo "- YOUTUBE_DATA_API_KEY present: ${{ secrets.YOUTUBE_DATA_API_KEY != '' }}"
          echo "- SERPER_API_KEY present: ${{ secrets.SERPER_API_KEY != '' }}"
          echo "- GROQ_API_KEY present: ${{ secrets.GROQ_API_KEY != '' }}"
